### ISSUE TITLE
error

### ISSUE THREAD

**Issue by DragonfireHD98** [Aetheam/AntiBadPackets#1]
[NetworkSession: NemesisFire2348] Session closed: Bad packet: Error processing PlayerAuthInputPacket: Module BadPlayerAuthInput (Error ID: 429b-5eeb-5d67)
[17:34:16.042] [Server thread/DEBUG]: [NetworkSession: NemesisFire2348] pocketmine\network\PacketHandlingException: "Error processing PlayerAuthInputPacket: Module BadPlayerAuthInput" (EXCEPTION) in "pmsrc/src/network/PacketHandlingException" at line 33
--- Stack trace ---
  #0 pmsrc/src/network/mcpe/NetworkSession(403): pocketmine\network\PacketHandlingException::wrap(object pocketmine\network\PacketHandlingException#80071, string[38] Error processing PlayerAuthInputPacket)
  #1 pmsrc/src/network/mcpe/raklib/RakLibInterface(219): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[140] ..Wda@..T..........\.Avv.....,.|....p.}...........q...x.~.1.+.53c]....c..nU..3..)
  #2 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[149] ...7p.4..O.~...Ue...O...*{G.&u....x..Tj....C......7.g.4.6..1".K..HW.......5Q!..v)
  #3 pmsrc/src/network/mcpe/raklib/RakLibInterface(111): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#150838)
  #4 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #5 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\TimeTrackingSleeperHandler->pocketmine\{closure}()
  #6 pmsrc/src/TimeTrackingSleeperHandler(77): pocketmine\snooze\SleeperHandler->processNotifications()
  #7 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
  #8 pmsrc/src/Server(1699): pocketmine\snooze\SleeperHandler->sleepUntil(float 1708364056.0596)
  #9 pmsrc/src/Server(1067): pocketmine\Server->tickProcessor()
  #10 pmsrc/src/PocketMine(341): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
  #11 pmsrc/src/PocketMine(364): pocketmine\server()
  #12 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)
--- Previous ---
pocketmine\network\PacketHandlingException: "Module BadPlayerAuthInput" (EXCEPTION) in "plugins/AntiBadPackets_dev-14.phar/src/Zwuiix/AntiBadPackets/modules/Module" at line 25
  #0 plugins/AntiBadPackets_dev-14.phar/src/Zwuiix/AntiBadPackets/modules/list/BadPlayerAuthInput(66): Zwuiix\AntiBadPackets\modules\Module->flag()
  #1 plugins/AntiBadPackets_dev-14.phar/src/Zwuiix/AntiBadPackets/listener/ServerListener(20): Zwuiix\AntiBadPackets\modules\list\BadPlayerAuthInput->inboundPacket(object pocketmine\network\mcpe\NetworkSession#155001, object pocketmine\network\mcpe\protocol\PlayerAuthInputPacket#80082)
  #2 pmsrc/src/event/RegisteredListener(61): Zwuiix\AntiBadPackets\listener\ServerListener->onDataReceive(object pocketmine\event\server\DataPacketReceiveEvent#193172)
  #3 pmsrc/src/event/Event(63): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\server\DataPacketReceiveEvent#193172)
  #4 pmsrc/src/network/mcpe/NetworkSession(454): pocketmine\event\Event->call()
  #5 pmsrc/src/network/mcpe/NetworkSession(400): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\PlayerAuthInputPacket#80082, string[59] ...K.@,..B...B..ZBK*.B........,..B.........................)
  #6 pmsrc/src/network/mcpe/raklib/RakLibInterface(219): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[140] ..Wda@..T..........\.Avv.....,.|....p.}...........q...x.~.1.+.53c]....c..nU..3..)
  #7 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[149] ...7p.4..O.~...Ue...O...*{G.&u....x..Tj....C......7.g.4.6..1".K..HW.......5Q!..v)
  #8 pmsrc/src/network/mcpe/raklib/RakLibInterface(111): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#150838)
  #9 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #10 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\TimeTrackingSleeperHandler->pocketmine\{closure}()
  #11 pmsrc/src/TimeTrackingSleeperHandler(77): pocketmine\snooze\SleeperHandler->processNotifications()
  #12 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
  #13 pmsrc/src/Server(1699): pocketmine\snooze\SleeperHandler->sleepUntil(float 1708364056.0596)
  #14 pmsrc/src/Server(1067): pocketmine\Server->tickProcessor()
  #15 pmsrc/src/PocketMine(341): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
  #16 pmsrc/src/PocketMine(364): pocketmine\server()
  #17 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---

**Comment by Zwuiix-cmd** [comment]
try next version

**Comment by DragonfireHD98** [comment]
thanks the error is gone
